### ISSUE TITLE
Ability to use our own cloud storage that pulls the songs, bibles.,etc.,

### ISSUE THREAD

**Issue by franklinis** [ChurchApps/FreeShow#1048]
It would be great to know if Freeshow can provide a feature, where it can pull the data (Songs, Presentations, Overlays,etc.,) to our application from our Cloud (Azure, Google or even OneDrive, GDrive)

This provides option to use our centralized storage and several people can work from different PC's at the same time.

**Comment by thebiblelover7** [comment]
@Dcanadian There are already solutions such as Syncthing that work as P2P file synchronization. It might be better to just have a "one size fits all" solution. If you can set your FreeShow show directory in a synchronized folder, it might not need any code changes.

**Comment by klecu** [comment]
I'm trying Syncthing as well. One issue might be cross-platform compatibility (Windows/Mac/Linux desktop at least) because media URI's are stored as absolute path. I think I can overcome it with all Windows devices by using something like C:\Freeshow, but that isn't always where you might want the media stored and isn't cross-platform. Could you make the paths relative to the data location, or have a media location?

**Comment by mwb9aa** [comment]
@klecu 
In that case, use a folder config share like @Dcanadian mentioned and have a shared folder that all the media goes into and from which FreeShow, file explorer/finder apps, etc. access the media.

So on my NAS/computer where I store the files create a file share like \\server-name\media\. Use that share to store and access all media used in FreeShow.

**Comment by franklinis** [comment]
@thebiblelover7 I‘ll try Syncthing for this purpose. Thank you for your suggestion 😊
