### ISSUE TITLE
Import PDF file - Blank

### ISSUE THREAD

**Issue by AngangGuo** [ChurchApps/FreeShow#1075]
**Describe the bug**
When I import the PDF file, it shows blank pages, or first several pages are normal, the rest are blank.

**Reproducing**
File link [here](https://www.allen-heath.com/content/uploads/2023/06/Qu-Mixer-Getting-Started-Guide-AP10025_2-V1.9-1.pdf)

**Screenshots (Optional)**
![import-pdf](https://github.com/user-attachments/assets/42a7c916-28f3-4836-9f7d-83ca3dd0977c)

After I restart freeshow:
![import-pdf-restart](https://github.com/user-attachments/assets/941c853e-e220-4df2-850e-4a3bf9f90cee)

**Version (Optional)**
 - OS: [Windows 10]
 - FreeShow Version: [v1.3.2] 

**Additional context**
 - Similar problem when I using v1.3.0, v1.3.1 with Windows 11 on another computer

**Comment by vassbo** [comment]
It's a Chromium/hardware issue I can't do anything about the way it's implemented (unless I move to a third party PDF renderer which takes a lot of space). The PDF file is probably too large for the system to handle, it works fine on my computer. You can use an online PDF to JPG converter if it doesn't work.

But I think I will add a "View as one page" button as that will render one PDF document instead of 24 entire PDF documents and probably help with this issue.

**Comment by BondarenkoArtur** [comment]
Will it make it any better if during import it will convert PDF to images with resolution of main screen?
Part related to lyrics and Bible works pretty well, but issues with PDF and Powerpoint, is not allowing us to migrate to FreeShow from OpenLP.
We are using multiple stages heavily and we need frequently enough to show PDFs or PPT.
Any suggestions or options?

**Comment by vassbo** [comment]
@BondarenkoArtur You should use an online PDF/PPT to image converter if possible.
https://www.ilovepdf.com/pdf_to_jpg
https://cloudconvert.com/pptx-to-jpg

**Comment by vassbo** [comment]
I changed the PDF renderer, so it should hopefully work good in 1.4.0.
