### ISSUE TITLE
Add Crossfade for Media Transitions

### ISSUE THREAD

**Issue by jquyatt** [ChurchApps/FreeShow#1085]
**Describe the feature**
Currently, when fading between two slide images with the same background but different text, the background will dip dark in the middle. It would make for smoother, higher quality transitions to implement a Crossfade transition where one slide is actually morphing into the next

**Additional context**
It looks like this has already been considered, since there's some commented out code in [src/frontend/utils/transitions.ts](https://github.com/ChurchApps/FreeShow/blob/main/src/frontend/utils/transitions.ts), so this likely just hasn't been implemented yet:

```
// https://stackoverflow.com/questions/70531875/svelte-crossfade-transition-between-pages
// export const crossfade = cfade({})
// export const [send, receive] = crossfade
```

For reference:
https://svelte.dev/docs/svelte/svelte-transition#crossfade
https://stackoverflow.com/questions/70531875/svelte-crossfade-transition-between-pages

**Comment by vassbo** [comment]
It works fine if the media is added as background to the slide and not as a media item, that way the media will not reload on each slide load. Optionally if you need the media to be on the slides you can set the item transition to none. 

Currently crossfade is not possible, because we would need to render each frame and get the pixel values, so it will cost some performance.

It would be nice to have, but it's not needed in your usecase.

**Comment by vassbo** [comment]
It might be possible for HTML/SVG elements, but not for media without capturing the screen/direct access to the video frame. So closing for now until maybe the output rendering is reworked, but that's unlikely as it affects the performance too much unfortunately!
