### ISSUE TITLE
Add variable, Type dropdown hidden by modal bottom edge.

### ISSUE THREAD

**Issue by melonkernel** [ChurchApps/FreeShow#1118]
**Describe the bug**
When adding a new variable, the type is hidden.
So i could not select Text

**Reproducing**
Go to Functions
Click Variables
Click New variable in the bottom edge
On the Type Dropdown, click where it says Number (which is the default)
A dropdown opens
(you can only select it if you know to scroll down in the opened modal)

**Screenshots (Optional)**
<img width="1098" alt="Screenshot 2024-12-19 at 9 40 18" src="https://github.com/user-attachments/assets/ef6b932c-2a7e-4cca-82d9-e56901b57e20" />
<img width="1092" alt="Screenshot 2024-12-19 at 9 44 31" src="https://github.com/user-attachments/assets/6bac9587-7c44-4226-821a-40f468886f30" />

**Version (Optional)**
 - OS: Mac
 - FreeShow Version: 1.3.2

**Additional context**
The modal could grow (not overflow scroll), be slightly larger, or not have a higher z-index on dropdown

**Comment by vassbo** [comment]
Z-index does not work on this because of how it is positioned, I have tried many options.

You get a scroll bar so you can simply scroll down to select the option, it's not out of reach.

I don't think there is a good way to do something about this unfortunately. But please open a PR if you find a good solution.
