### ISSUE TITLE
Using a label for individual slides

### ISSUE THREAD

**Issue by kinghamr** [ChurchApps/FreeShow#1140]
Is there a way to add a label slides feature with different colors by chance
This is not a Group since Group is being used for actual Chorus/Verse/Bridge/Pre-Chorus/etc

So, for example, we edit things on the fly, and when we perform the songs, the worship leader changes how the song is performed every time, so the song is performed different every time and would like a note or label in the slide section (like "x2" or "X2" or "REPEAT" etc) without having to change things in the "NOTES" slide
And it should show up on the bottom of the slide title on the left or right side; doesn't matter on location

![image](https://github.com/user-attachments/assets/f6e3fbd8-6983-417a-811b-38ae756fb098)
Just like on the bottom right of this section

Would it be possible to add that by chance?

**Comment by jerm00** [comment]
my church worship team does something similar. the common songs all have many layouts (arrangements) that i've added, and the nice thing about freeshow is you can name the layout with a very long descriptive name so i use names like "with repeat verse 2 because josh felt the song was too short"

if there is a verse or bridge that repeats, i use notes on the stage display to put a counter per slide so the musicians can see at a glance how many times they've done that slide, i put something like "Bridge: 2 of 4" next slide "Bridge: 3 of 4" and etc. the downside is that, yes, you have to add 4 identical slides under 1 bridge entry. if you add bridge 4 times, they'll all have the same notes. it would seem to me that changing that functionality would be difficult to implement, and might get messed up when adding multiple layouts (arrangements) of each song, but maybe i'm wrong

**Comment by kinghamr** [comment]
I think having an added section to here as "notes" would be quicker due to the fact our worship pastor/lead singer may like to either just repeat a section or a technical note on a slide for that specific slide during worship
![image](https://github.com/user-attachments/assets/ab6c0918-eeae-4151-a74c-de70a6c33f90)

**Comment by vassbo** [comment]
@kinghamr For your use it's much better and faster to just drag in another verse to the layout in that scenario, you should never need to type "x2" or "repeat"!

@jerm00 In your scenario maybe you can make use of the "Progress" item and set it to "Groups":
![image](https://github.com/user-attachments/assets/700fc907-eaa9-4305-aa09-9fc597b2986c)

Closing for now, but if there is a useful use case for this I'll consider it.
