### ISSUE TITLE
Few bugs relating to Connections

### ISSUE THREAD

**Issue by kinghamr** [ChurchApps/FreeShow#254]
Few bugs I have noticed
In OutputShow
The display is not showing properly or is very delayed on external devices

In StageShow
I have a slide that reflects the "Current Output" (which is the whole screen) and that is not showing properly and is playing with the slide layout

<img width="1512" alt="Screenshot 2023-09-12 at 11 07 03 PM" src="https://github.com/vassbo/freeshow/assets/38868273/27158128-d6df-49eb-89c5-65a2e0101546">

<img width="1512" alt="Screenshot 2023-09-12 at 11 05 11 PM" src="https://github.com/vassbo/freeshow/assets/38868273/83fe06c1-8af1-411f-ba6b-6bd31d1cd33a">

<img width="1512" alt="Screenshot 2023-09-12 at 11 05 02 PM" src="https://github.com/vassbo/freeshow/assets/38868273/e82aad04-94e0-48a2-99a9-2a30ff9528b2">

**Comment by vassbo** [comment]
1. Maybe slow computer or slow connection? It works fine in my testing at least.
2. I haven't implemented the "Current output" feature properly

**Comment by Sergios199703** [comment]
The problem is that individually these styles work, but when I make 2 screens, they do not work correctly on two screens, what could be the problem
![image](https://github.com/vassbo/freeshow/assets/145131268/dbbf4c27-ee89-499f-94ec-453f352b83de)


![image](https://github.com/vassbo/freeshow/assets/145131268/02757659-6c60-40c7-93a4-f0b891dbae0d)
and also when I click below to display the text, it is not clear in what style it displays it, but when I create a show, it displays normally

**Comment by Sergios199703** [comment]
![image](https://github.com/vassbo/freeshow/assets/145131268/140df10f-0e86-47f1-b2c8-7e9a82aa1067)
when there is one screen and I created a show of three poems, everything is fine, but when there are two different styles and the size of the auto text, it does not work correctly

**Comment by vassbo** [comment]
@Sergios199703 Auto size is not currently working properly for direct scriptures, but it works when creating a show from the verses.
It looks like your two outputs have two different styles, so what do you mean it do not work correctly?

**Comment by kinghamr** [comment]
I’m using the latest mac computer m2 chip and my iphone on a wifi tether

**Comment by vassbo** [comment]
Okay, does the OutputShow work fine when opening in the browser on the same computer? Or is it lagging on your mac as well?

**Comment by Sergios199703** [comment]
@vassbo I want one screen to have access to the hall, that is, in a large size, regardless of the text, so that it automatically increases or decreases, and the second screen for broadcasts, so that the text is from the bottom and also automatically adjusts to the size of the text, or how to do it differently?
now output 1 is correct on the monitor no
![image](https://github.com/vassbo/freeshow/assets/145131268/4aa688d7-b162-4efd-95b8-ee6af3796acf)
but here it is correct on the monitor, but not on output 1, how to make it work, because without an automatic text spreader it is not realistic to work constantly or the text is very large or very small
![image](https://github.com/vassbo/freeshow/assets/145131268/eb2b5850-8004-4ae8-9f6c-e5d61957f2d2)

**Comment by vassbo** [comment]
Oh, I understand. I'll see what I can do.

**Comment by Sergios199703** [comment]
@vassbo thank you, by the way, thank you very much for the Ukrainian translation

**Comment by kinghamr** [comment]
OutputShow works fine when I open it the same browser
I'm using an iPhone 14 Pro Max web browser

**Comment by vassbo** [comment]
Okay. Then it's the network creating the issue, I might add an option to decrease the frame rate so it won't lag as much.

**Comment by kinghamr** [comment]
Meanwhile, StageShow has no issues with sharing and I'm only showing a
black screen with text
And the network only has 2 connections, my laptop and my cell phone.

**Comment by vassbo** [comment]
Yeah, but the stage is just maximum a kilobyte of data, when the content changes. But the output sends a few megabytes each time the window frame updates at most 20 times per second.

**Comment by Sergios199703** [comment]
I wanted to know how things are going with auto text size on two or more screens

**Comment by vassbo** [comment]
I haven't had the time to work on it yet, but will possibly be done within a few weeks.

**Comment by Sergios199703** [comment]
there is a problem when opening any show, it seems to blink twice then opens, but the problem disappeared with auto size

**Comment by vassbo** [comment]
The text "blinks" when calculating the auto size, if that's what you meant. I can try to increase the speed of it.

**Comment by Sergios199703** [comment]
so that's what I mean, if it's real it'll be good
