### ISSUE TITLE
Dynamic textbox

### ISSUE THREAD

**Issue by Benjamin72070** [ChurchApps/FreeShow#284]
I would like to request that there be an option to dynamically size the textbox with padding.  I see that you have the opposite implemented with the auto-resize switch for the text.  The reason this does not work for me is that if I set a text box a certain size, but have lyrics of varying length lines, the text is not a consistent size.  

Videopsalm does this for scripture and it is infuriating because the user has no way to turn it off.  Short verses are huge while long verses are tiny.  They have a workaround where you can convert a scripture into a song and be able to control the size consistently across the entire passage.

I am not sure how this could be implemented seeing as it would not work if both the text and the textbox was set to auto-resize.  I wish I was fluent in JavaScript and Electron.  That way I might be able to contribute code to the project.

**Comment by vassbo** [comment]
You can set the "Background color" on the text (under "Style" in the textbox styles), instead of the item to get the background to dynamically wrap around the text. This is not perfect, and currently you can't set the opacity (I'll see if I can make this possible).

But implementing it in another way would be too much work, because I think you're better off just having one or two fixed sized textboxes and break the text into multiple, if it overflows.

**Comment by Benjamin72070** [comment]
The problem with setting the background color under style in the textbox area is that if you do it under templates and override the style, it does not show up on the alternate output.   I only want this effect on the livestream output not the main output.

**Comment by vassbo** [comment]
Yep, this is probably what you are referring to here: https://github.com/ChurchApps/FreeShow/issues/283
I will see if that can be fixed.

**Comment by Benjamin72070** [comment]
Ok, that will make things better.  I really do appreciate the work.  Thank you.
