### ISSUE TITLE
HOW TO ADD THE THEMES FROM PROPRESENTER TO TEMPLATES?

### ISSUE THREAD

**Issue by SKU003** [ChurchApps/FreeShow#327]
Just like the title, wanted to know if it's possible, and If we could add them to template both motion and still themes?

![Files_vIytcIRbr7](https://github.com/ChurchApps/FreeShow/assets/117542049/7f96d1e0-331e-44c2-8e6b-8233bf5641c8)

![Files_7I671f9m1x](https://github.com/ChurchApps/FreeShow/assets/117542049/6bf50dce-62d1-40b6-8268-4e45386e7bd8)

**Comment by vassbo** [comment]
Sorry, you can't do that. And I don't think support for it will be added, because of the differences between the two. So you'll have to recreate it manually as close as you can. But there are plans to create a simular "Export/Import" to the way PP themes works, so people can share their "Templates" with each other.
