### ISSUE TITLE
Issues with MIDI In macOS Sonoma 

### ISSUE THREAD

**Issue by shadowfax2112** [ChurchApps/FreeShow#338]
Hello,

Having some strange issues with receiving MIDI messages in FreeShow.
1 - When adding a MIDI action in Settings->Actions it does not take effect until after saving, quitting and opening FreeShow.
2 - Was having great difficulty getting it to recognize MIDI input on Channel 1. After several tries and using the Update Values when receiving a MIDI input slider it was recognizing Channel 1 as Channel 144.
3 - It seems to only recognize NoteOff messages, can't get it to work with NoteOn
4 - Probably due to the above it does not recognize Velocity parameter. I tried using the Select Slide by Index it always recognized the velocity as 0 and went to the first slide. (I'm pretty sure I was trying with NoteOn but don't recall)

I use an app call MIDI Monitor to confirm the midi data being sent is correct. Let me know if I can do anything to help debug.

Thank you

**Comment by shadowfax2112** [comment]
Just realized Channel 144 is 0x90 which is the entire Byte for noteon

**Comment by homemadestea58** [comment]
I am experiencing identical issues but with Windows. 
My setup is as follows:
- Companion -> Midi-relay
- Midi-relay -> LoopMidi
-LoopMidi -> Freeshow

Companion to Midi-relay to LoopMidi works fine because I have tested it with MidiView and it shows the correct midi messages coming through, but there is no visual response from Freeshow as to whether it is connected to that midi port and it doesn't update when I send through the Midi command.

Interestingly I also found that when I add a `Send Midi Out` action directly to a slide and activate it, it will send out an `All notes off` message on every channel 1-16, and not output the Midi message programmed.

I have tried using NoteOn and NoteOff but that doesn't seem to help.

Any ideas on what I might have missed?

**Comment by shadowfax2112** [comment]
Hi, it looks like v1.1.1 has fixed several issues, Great!.
The channel issue still exists and can be fixed quite easily.
I found by modifying src/electron/utils/midi.ts line 84 to be:

let values = { note: msg["1"], velocity: msg["2"], channel: (msg["0"] & 0x0F) + 1 }

that the channel number is correctly interpreted.

I'm not a proficient enough programmer to contribute anything beyond this but hope this helps.

**Comment by vassbo** [comment]
Great! Thank you. 😊

**Comment by homemadestea58** [comment]
I'll test it when I get back to my desk, and if it doesn't work, I'll spin up a dev version of Freeshow and try to debug it. I have a bit of Midi gear here so I'll see what I can do.

**Comment by shadowfax2112** [comment]
Quick Update, I was still having strange issues with MIDI but found it had more to do with all the MIDI devices I use sending all sorts of messages, especially MIDI clock. I installed a program called MIDIpipe which allowed me to filter out all messages except NoteOn/NoteOff and then everything started working smoothly. 
I found adding this line to the receiveMIDI() function helped: 
port.connect(function (msg: any) {
            // console.log(msg)
            if (!msg.toString().includes("Note")) return

but unfortunately I can't run FreeShow in the dev environment (Visual Studio Code) on MacOS Sonoma, it won't load videos for some reason. So using MIDIpipe and the compiled version worked for me.

FYI: the select slide index from velocity can't select slide 0 as a NoteOn with velocity 0 is detected as NoteOff. 
But I was able to successfully run my presentation in rehearsal and everything ran smoothly.

Thank you for all your great work!
