### ISSUE TITLE
Output screen in Stage View

### ISSUE THREAD

**Issue by abhishikthraj** [ChurchApps/FreeShow#363]
I have 2 audience outputs(Audience Slides and Green Screen) and a Stage View. I have added the output screen item (on the bottom right) in the stage view and selected the output to be green screen (Please refer the screenshots below for better understanding). I'm able to see the correctly on the layout preview (on the left)  but in the stage view edit screen I see the audience slides output and on the actual stage view output I see a blank screen.

Although if I select audience slides output on for the output screen, it is showing correctly for layout preview and edit preview but I see it blank on the output screen.

![image](https://github.com/ChurchApps/FreeShow/assets/58181678/b9c6220c-bf32-46f7-b45c-26d7d5531474)
![image](https://github.com/ChurchApps/FreeShow/assets/58181678/b03a6827-052b-4570-8943-387f54943bc9)
![image](https://github.com/ChurchApps/FreeShow/assets/58181678/2bfcc7a0-f3bd-4fc3-abec-58f7a759e362)
![image](https://github.com/ChurchApps/FreeShow/assets/58181678/6c0261e5-cecf-47fc-8030-523dff025ab2)

**Comment by abhishikthraj** [comment]
When the output is audience slides this is the scenario. Check the stage view output screen.

![image](https://github.com/ChurchApps/FreeShow/assets/58181678/e4ce18c8-1e07-40bd-995e-5e8c394a1116)

**Comment by vassbo** [comment]
Thanks. I'll take a look.

**Comment by FelixHeppner** [comment]
I can confirm: the output screen item is blank in actual stage output while preview in editor and in layout overview is fine.

**Comment by FelixHeppner** [comment]
Stage output still shows mostly blank areas only for me in v1.1.2 on Linux. I have only one main output that I try to mirror along with next slide, comments and a clock on the stage display. Sometimes the clock is shown but nothing more. The preview and the Stage Display Editor show everything correctly. But the real output is empty via  hdmi, ndi and browser interface.
I am running the app image. In the console I can see an error message:

Failed to load window: {"errno":-2,"code":"ERR_FAILED","url":"file:///tmp/.mount_FreeShQClRVN/resources/app.asar/public/index.html"}

But I am not sure whether this is connected.

**Comment by FelixHeppner** [comment]
I found out the display might work to some degree depending on the used elements. 

The StageOutput is messed up if I do include notes for current slide (!?). Sometime the text content for current slide might be shown sometimes only for the first slide. Basically this is not usable. Since I don't have a lot of comments this is not an urgent problem

The next slide element only shows text content but nothing when the slide is an image (for example imported power point / pdf content). Is this intended? While there is the possibility of preparing slides for the message in FreeShow a typical workflow is that whoever comes in brings pptx oder pdf as a presentation and in this case the preview of next slide does not work

**Comment by vassbo** [comment]
Thanks. I'll take a look.
