### ISSUE TITLE
Include Media and Audio files in Export & Import

### ISSUE THREAD

**Issue by colanct** [ChurchApps/FreeShow#401]
Media and audio files are presently excluded from Export & Import functions.  These files have to be processed separately. 
Having a single, consolidated export/import will significantly improve portability.

**Comment by vassbo** [comment]
Adding the media directly to the shows might be an option sometime. But right now I think I can add an option to copy media files in shows to one selected location.

This should not be an issue though, because as long as you have a good system where you store most of the media files in one folder you can just copy that entire folder, and add it again to the drawer and all of the media files should work in the shows.

**Comment by vassbo** [comment]
I added a button with the Export/Import buttons to "Bundle all media files", this will copy the media backgrounds & audio it can find from all the shows into one folder, you can then manage them how you would like. To use them elsewhere, make sure to add the folder with all the files to the media drawer, that way FreeShow can auto find the files if it can't find them at the original location.

**Comment by colanct** [comment]
This is good solution. Thank you.

**Comment by simonseres** [comment]
> I added a button with the Export/Import buttons to "Bundle all media files"

Sorry - where can I find this button? 😳

(trying to sync media across instances using a file sync tool like Dropbox)

Edit: Never mind. Found it (Settings -> Other)

**Comment by vassbo** [comment]
@simonseres Cool. I'm gonna make it more automatic soon, as per this issue: https://github.com/ChurchApps/FreeShow/issues/1925
