### ISSUE TITLE
Textbox parameters are changed immediately when selecting an attribute section header on the edit screen

### ISSUE THREAD

**Issue by colanct** [ChurchApps/FreeShow#446]
Selecting a section header in the attribute/settings panel when editing a show changes multiple parameters within that section to (what may be) a default setting.  Expected behaviour is for changes to be made only once a specific attribute is selected and changed.  

For example: when selecting the Textbox > Lines header, Line height and Background colour are changed immediately.

**Comment by vassbo** [comment]
Thanks. Most of the time it's helpful to set some default values when activating a style section, because that's what people want, at least in the case of shadow, etc.
I see your point, and have thought about it. But I don't think this is a big issue, because you don't often change those values very often, if you do you should create a template for it anyway. Hope this makes sense.

**Comment by colanct** [comment]
Thank you for your response.  However, the logic doesn't make sense to me.  So, maybe, there's a misunderstanding.  To help clarify the issue, here's an example of a typical scenario where the present functionality seems incorrect or unintuitive.

- An established show (a lyrics slide) needs to be tweaked to increase word spacing.
- Select Edit > Textbox.
- Style section headers are displayed collapsed.
- Select TEXT section header, to expand and (presumably show present settings for that section).
- On selecting the TEXT section header, text is immediately changed to uppercase (expected behaviour is for no changes to be made when expanding section header).
- No case change is wanted, and this will have to be undone.
- Selecting Reset, undoes the capitalisation, but also collapses the section (expected behaviour is for the section to remain expanded).
- The sequence repeats when the section header is expanded again.
- This behaviour also occurs in the other sections (for example: selecting the LINES section header unexpectedly changes background colour from none to black). 
- If a user just wants to view present settings within a section, simply clicking on a section header changes the settings, unexpectedly.

To me, it is unintuitive to apply changes without an explicit selection/change. Please let me know if I've misunderstood the design intention for the whole Textbox editing function.

I hope this helps. Thank you.

**Comment by vassbo** [comment]
I understand. I can make it not change that much when clicking "Text" or "Lines", but for all the other sections it makes sense to apply some preset values. Hope this is okay.

**Comment by colanct** [comment]
I just noticed that functionality is slightly different when editing a _scripture_ slide.  For those, all style/formatting sections are expanded when entering Edit mode.  And then, when selecting a Textbox to edit, the top three sections (Align, Text, Lines) are expanded.  This seems better, as the problematic applying of defaults on section expansion, goes away.

Please advise where the preset values that you mention above are defined.  Is it in the template?  

I see the same issues, as described in the scenario above, occur when editing a Template (for example when expanding the ALIGN section, the text unexpectedly changes from centre aligned to left aligned).  So, it seems there may be another level of defaults, or maybe, I'm misunderstanding something.

**Comment by vassbo** [comment]
The sections/buttons are for applying styling, (not just opening a menu). The sections are expanded when the values are changed from the default, like the scripture templates. The preset/default values are pre chosen to the most likely.

When clicking "Align" you want to change the alignment of the text, (the default is centered, and section is closed), most of the time you want to change it to be left aligned, that's why it changes to that. If you want it to be right aligned instead, just click that option, it's not any more button presses. If you didn't want to change anything after all, just reset it.

As I said, I will change two of them to not change as much styling. :)

**Comment by colanct** [comment]
Thank you for your helpful explanation.
