### ISSUE TITLE
Looping video bug

### ISSUE THREAD

**Issue by Lycol50** [ChurchApps/FreeShow#506]
After playing the video, it would loop but the loop is not enabled, otherwise, when the loop is enabled it would not loop.

**Comment by vassbo** [comment]
Looks like it works like it should. When the loop icon in the media output content (different to the show "Media" tab) is colored it should loop, and when it is white it should not loop.
When playing from a slide as a background it loops by default, and when playing from the drawer it does not loop by default.

If you still have issues, could you provide some screenshots or more details on where exactly this is an issue?

**Comment by Lycol50** [comment]
Hello, i will demonstrate two scenarios: which is **when i didn't clicked the loop** and **when i clicked the loop**

**Without clicking the loop button on media output**
[not-loop.webm](https://github.com/ChurchApps/FreeShow/assets/46164440/034e16aa-2af7-4a1f-8109-f54cbf25dce4)

**With clicking the loop button on media output**
[loop.webm](https://github.com/ChurchApps/FreeShow/assets/46164440/8669c618-dccb-488e-a097-d732aee0512b)

This issue also applies when playing from Media tab

**Comment by Lycol50** [comment]
One of my alternatives to **not loop** is to add actions to the slide with `Next Slide Timer`, by converting the video's duration to seconds and insert into `Next Slide Timer` dialog box

**Comment by vassbo** [comment]
Okay, I have taken a look, and everything works as expected. Looks like your theme makes it hard to tell when the loop is turned on/off. (I will probably have to do something about that..) The video loop is activated by default, so when you in the first video did not click it, the video looped. And when you in the second video clicked to turn off, it did not loop.

You can toggle the video loop in the show "Media" tab:
![image](https://github.com/ChurchApps/FreeShow/assets/17619496/b7595f4f-3f85-4846-92ef-4193438705aa)

What you can do also, is to right click the slide with the video, and set the action "Next on media finished", because that will go to the next slide when the video has reached the end.
