### ISSUE TITLE
Windows - Freeshow installs but doesn't run

### ISSUE THREAD

**Issue by JayLocklear** [ChurchApps/FreeShow#542]
After installing on Windows 11, I receive a dialog box with the following error message: "This file does not have an app associated with it for performing this action. Please install an app, or if one is already installed, create an association in the Default App Settings page.

![image](https://github.com/ChurchApps/FreeShow/assets/170843275/c671612d-7161-4226-ba2a-34e3f1a64682)

When I dismiss the dialog and double-click the shortcut, the program doesn't run.

**Comment by vassbo** [comment]
Looks like the shortcut no longer links to a valid path. Please go to `%AppData%/Local/Programs/freeshow` and see if the "FreeShow.exe" can be opened from here, if it can you can create a new shortcut.

**Comment by JayLocklear** [comment]
The program doesn't open from the %AppData% location. When I double-click, it spins but the program doesn't run. I don't see any activity in Task Manager, either. I also tried running it as Administrator just to rule out any kind of random permission issues.

**Comment by JayLocklear** [comment]
Here's what I got: 
![image](https://github.com/ChurchApps/FreeShow/assets/170843275/ad264532-a7af-48f5-aed4-dd6da12ae2c0)

I checked the properties for the file, and it looks like I should be able to run it.

**Comment by vassbo** [comment]
Thanks. I have not encountered this issue before, and could not find much detail of it on the web.

Please try opening the command line as administrator if you haven't already, and try opening it again, just to see if there is another message.

You can also try installing the previous version, because that was code signed, just to see if that might be the issue, maybe the antivirus program does not like it:
https://github.com/ChurchApps/FreeShow/releases/download/v1.1.5/FreeShow-Setup-1.1.5.exe

**Comment by vassbo** [comment]
Any updates on this @JayLocklear? Did you try running the .exe from the command prompt with administrator privileges?
