### ISSUE TITLE
Importing PowerPoint

### ISSUE THREAD

**Issue by douglas-jordan** [ChurchApps/FreeShow#549]
When I import a powerpoint file it puts the first slide as the last and slide 2 in the file is now 1 in freeshow.
There does not appear to be anyway to drag it back to the top or beyond the visible list.  So I selected the slide and clicked edit->copy and selected the first slide and clicked edit->paste.  It then adds the copied slide as the last slide so now there are two of the same at the end.  My expectation was that it would paste the copied slide above or below the selected slide.

I went through the import process several times and the result was always the same.
System is Windows 10.

**Comment by vassbo** [comment]
Has this happened with multiple PowerPoints?
The paste currently adds the slide last always, but you should be able to hold it and drag it to the start.

**Comment by douglas-jordan** [comment]
I import a powerpoint file, tried different files.  There are over 50 slides in the powerpoint file.  The first slide is always set as the last slide into an empty show.  Yes the last slide can be dragged to the top but only through the visible list, there is no way to drag it to the top in one step.  It takes many steps to move it over and over to get it to the top, scrolling the list between steps. 
There are other editing idiosyncrasies:
Select a slide on the left, select ALIGN on the right and immediately the slide changes to left justified even though nothing else has been selected to change the alignment.
If you backspace and text is moved to the above line, the cursor | then moves to the beginning of the line vs staying in front the character that it was next to on the previous line.  This is very uncharacteristic of edit box behavior.
Typical keyboard shortcuts for moving to the beginning or end do not work. For example my expectation when clicking on the slide list and then Ctrl+Home the list would move to top.

**Comment by douglas-jordan** [comment]
I tested pdf import to evaluate any differences, so I saved the powerpoint file used in the tests above as a pdf and import of the pdf does not change the slide order, however none of the text can be edited even though pdf file was saved as text and not images.

**Comment by vassbo** [comment]
- Have not been able to recreate the first slide being last.
- If you hold the slide you want to move just at the top of the slide area, it will auto scroll so you can move it to the top in one go.
- The Align is intentional. When clicking on align you apply a style, and in most cases you want to change the text to left align, if not just click on the new one, or click reset, in most cases it's not more clicks.
- The cursor behaviour should be improved in the next update.
- Will see if I can add more shortcuts eventually.
- The PDFs are imported as images, regardless of the content.
