### ISSUE TITLE
Flagged as unsafe

### ISSUE THREAD

**Issue by DouglasLaughlin** [ChurchApps/FreeShow#556]
Your program looks fantastic.   I especially love that you included NDI in free software.    My issue is that installation stops and lists a virus in FreeShow and tells me to not install.

**Comment by vassbo** [comment]
Hi, thanks. This might be an issue with the antivirus program, you can add it to the whitelist if possible. If you get a blue popup on Windows that says it is unsafe, you should be able to press the "Read more" button, and "Run anyway".

We should get it code signed very soon, so that might also fix this problem.
https://github.com/ChurchApps/FreeShow/issues/362

If you are still stuck, please provide some more details on the exact problem.
