### ISSUE TITLE
Better documentation required

### ISSUE THREAD

**Issue by lof747** [ChurchApps/FreeShow#557]
Great job in writing this piece of software, we're about to trial it this Sunday.

We are having trouble following through the docs, possibly further clarification is needed to answer these questions:
1. Variables, are variables just a placeholder we set in FreeShow? Or can it actually be set to a tagged-like style e.g. {{song_name}}, if it's tagged-like style then we'll need to know a full list of supported variables.
2. I'm yet to find out how to customize a layout for scripture, so far I have duplicated the default scripture layout and changed the positioning etc, however if a better example of layout can be shown it would be great
3. Took me a while to work with List/Timer/Clock because I wasn't aware you need to click on the item button to make changes (was right clicking hoping to see options), in documentation we'll need step-by-step (preferably with pictures) of how to use these features

All in all, keep up the good work :)

**Comment by vassbo** [comment]
I agree, need to improve sometime.

1. Not at the moment, but that would be nice.
2. You have to edit or create a new template however you like, and then change the active template in the right of the "Scriptures" drawer section.
3. Makes sense.

Thank you!

**Comment by Mar4-dev** [comment]
@vassbo A big thank you also from me. God bless you!
I agree, especially with the 2. point.
Not quite sure how to create an appropriate lower third with text and reference for the scripture tab. I've added a new template and created two text fields: One for the text, and a smaller one above for the reference. After that I select the template from the Scripture tab, but it doesn't seem to work. The Bible text has been cut off, and I changed the "Meta" for the reference within the template to left-oriented, but it is still centered.
There is also a problem with the book names for imported XMLs. Either the book is not recognised at all (as in the screenshot) or the book names are displayed in English (instead of German). How can I change this?

![Scripture erros_FreeShow](https://github.com/ChurchApps/FreeShow/assets/71387911/aab49dd0-4c27-4dfc-a1cf-94317df73ad3)

**Comment by Mar4-dev** [comment]
I found the dynamic size setting, this is very helpful! :)
For the orientation of a text element: If I click on a text, I'm able to choose the orientation but it seems to not affect the output. If I highlight the text, the orientation is always center and locked.

**Comment by vassbo** [comment]
Okay, something was probably wrong with the bible you imported because it does not have book names.
Will see what I can do about the text alignment.
