### ISSUE TITLE
Add Teleport support for OBS

### ISSUE THREAD

**Issue by joelgraff** [ChurchApps/FreeShow#585]
Suggest adding Teleport support for OBS in lieu of NDI. It works better and is much easier to set up on the user side

**Comment by MrDogeBro** [comment]
To chime in, it would be nice to have as another option, but I don't think it should replace NDI since NDI is a standard tool used across video workflows, and having NDI built into FreeShow allows it connect to all of the NDI tools already out there.

**Comment by vassbo** [comment]
@MrDogeBro I agree! NDI will definetly stay, even if we add support for other formats.

**Comment by vassbo** [comment]
Looking into it more I could not find an NPM package to run Teleport on Node. When that comes I might be able to implement it, but until then I won't do it unfortunately, mostly because there exists an [NDI package](https://github.com/DistroAV/DistroAV) for OBS that works fine after first time setup!
