### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by Beniamin137** [ChurchApps/FreeShow#615]
Please add an "Edit" feature for bible. Templates are ok but we need something better. We don't want to make so many presentations for some verses... to much work.

**Comment by Beniamin137** [comment]
And something to edit bible for livestreaming

**Comment by vassbo** [comment]
If you want to make permanent changes you can edit the XML/JSON file iteself (if you have the rights). Also you can create a show if you want to make small changes (would not be more work than direct editing if it's one time). Or as you say use templates to change the style directly.

See more here: https://github.com/ChurchApps/FreeShow/issues/573

The reasoning behind this is because some scriptures are licensed, and should not be allowed edited.
