### ISSUE TITLE
NDI Only output

### ISSUE THREAD

**Issue by SWederell** [ChurchApps/FreeShow#621]
I think it would be good to see an NDI-only output. One where you can configure the resolution and refresh rate independent of a monitor/projector.

**Comment by vassbo** [comment]
You can do that by creating a new output and just using NDI (Turn off "Always on top", and move it out of the view). The thing is the NDI has to record the content from an actual window, so it has to be an actual window. But I will see if I can auto hide it at some point if it's just used for NDI.

Also if you are going to show the same content that the actual projector screen there is no point in setting a custom resolution/frame rate, because that's only used for NDI anyway (if it's the same aspect ratio). The normal output windows have vector fonts, and full res video playback.
