### ISSUE TITLE
Scriptures not working properly on all platforms v1.1.9

### ISSUE THREAD

**Issue by JVoorn85** [ChurchApps/FreeShow#630]
If you go to scriptures tab the whole app hangs and is unresponsive.

**Comment by funnysloth** [comment]
Same on windows pc

**Comment by Bagel94** [comment]
06/30/24 - We use Linux at our church, and this morning when I pulled up a scripture it pulled the current reference, but the verse was absolutely the wrong one. Was looking for 2 Cor. 4:18 but some how it pulled from like Genesis 1

**Comment by EM-jrchem** [comment]
I have experienced the same unresponsive issue with the scripture tab

**Comment by colanct** [comment]
I too am experiencing this on two Win 10 PCs.  On both, FreeShow hangs immediately when selecting the Scripture drawer, which appears blank.  The only way to close FreeShow is via the Task Manager.

On one PC, where v1.1.9 was installed on top of v1.1.7, did not have this problem.
The problem occurred after that v1.1.9 was uninstalled (and leftovers removed using Revo), and then v1.1.9 reinstalled.

The following entry is made in the error log:
"type": "unhandledrejection",
			"source": "See stack",
			"message": "Cannot convert undefined or null to object",
			"stack": "TypeError: Cannot convert undefined or null to object\n    at Function.keys (<anonymous>)\n    at e.$$.update (file:

Please advise if you identify a work-around (other than rolling back).

**Comment by vassbo** [comment]
Will be fixed in the next version!

Workaround (if you can use local bibles):
1. Locate the program data location (Windows: %AppData%/freeshow)
2. Open "settings_synced.json".
3. Find the "scriptures" key, and add this to the start:
```
"fix": {
    "name": "Fix"
},
```
4. Open the "settings.json" file, locate the "drawerTabsData" key, and replace the "scripture">"activeSubTab" key with "fix".
5. Open the program, and locate the scriptures tab. (Don't click on any API bibles, or collections), only local bibles work, but this allows you to import this.

If you can't figure this out, you can wait for the next release or downgrade to 1.1.7.

**Comment by colanct** [comment]
Thank you.  That resolved the issue on both PCs.

**Comment by TPaulManohar** [comment]
Same issue,
If we trying to search for a verse in scripting it pulled from Genesis 1:1.
Eg; Trying to add Psalms 137 entire chapter, it pulled from Genesis. To fix means, we need to click few books multiple times then search or Manually need to add. 

I think loading the Bible has issue

In Scripture Tab Right button and options need to implement, Like 
. Add to Project

**Comment by vassbo** [comment]
@TPaulManohar Do you have this issue in version 1.1.9? Also if you click the "New show" button in the bottom right is will be added to the project.

**Comment by TPaulManohar** [comment]
yes @vassbo This issue is in V1.1.9. And yes after selected the verse and click New Show button it added to the project, but it picked Genesis 1.

Recently I noticed in Mac M2 Pro, If we select Scripture is not responding, and Even rest of tab also not working like Shows, Media, Audio, Templates, Calendar, Functions. After closed the app and restart application if we click rest of the tabs it works, if we click again scripture tab it won't work, not responding other tabs as well.

**Comment by Jsiwolowski** [comment]
The last good working vesion is 1.1.7

**Comment by vassbo** [comment]
This should be fixed in this release: https://github.com/ChurchApps/FreeShow/releases/tag/v1.2.0
(Marked as prerelease currently, in case any major bugs have occured, but should not.)

We need more people testing the prereleases to prevent things like this from happening, you will be able to find them on the website as well: https://freeshow.app/downloads

**Comment by colanct** [comment]
Confirm drawer freezing issue is resolved in v1.2.0.
Adding and navigating API and XML bibles is fine now.
Thank you.

**Comment by TPaulManohar** [comment]
@vassbo  We tested v1.2.0 scriptures, it is works as expected. And searching Bible references also working correct.

Thanks you
