### ISSUE TITLE
[BUG] Editing text in list view update other text area (1.1.9)

### ISSUE THREAD

**Issue by budirec** [ChurchApps/FreeShow#640]
After updating to v 1.1.9, when you edit a text in list view, it will update the text adjacent to it

https://github.com/ChurchApps/FreeShow/assets/11371076/8b0db968-babf-49ad-858a-26b11462af08

**Comment by jzongker** [comment]
Adding notes on how to reproduce for now.  This happens when editing from the List view on the Shows tab while using a template with multiple text areas.  If you go to the Edit tab and make the changes it appears to work normal, which can be a work around until we get this fixed.
https://github.com/ChurchApps/FreeShow/assets/1447203/8b87607c-b753-4fdc-b96a-8cacd55e84fe

**Comment by budirec** [comment]
Apparently clicking the template again (to make the list shuffles through textarea) will cause the texts to disappears too.
