### ISSUE TITLE
App Freezing

### ISSUE THREAD

**Issue by cnwangwu** [ChurchApps/FreeShow#654]
V1.1.9. App freezes after 3 mins of use or consecutive clicks on my two windows laptops. Also, the bible section is empty.

**Comment by abhishikthraj** [comment]
@vassbo I'm just adding my log files here for your reference instead of creating a new issue. The app is freezing while switching specific tabs. Also for some reason, for the scripture tab the selected scripture is being maintained to the one the I select for the first time and even after going to different verses, comes back to the first selected verse when I switch tabs and come back to scripture tab.
[error_log.json](https://github.com/user-attachments/files/16132653/error_log.json)
[error_log.json](https://github.com/user-attachments/files/16132673/error_log.json)

**Comment by vassbo** [comment]
Probably related to this: https://github.com/ChurchApps/FreeShow/issues/630
