### ISSUE TITLE
Syncing Issue

### ISSUE THREAD

**Issue by EStahr3337** [ChurchApps/FreeShow#670]
We just started using FreeShow, and I can't seem to get syncing to work. I create a project and get everything ready on my laptop. I sync it to the cloud (I set up the backing up to Google Drive). But when I log into the presentation computer, the projects and media are not there. I've tried using versions 1.1.7, 1.1.8, and 1.1.9 and run into the same issue with each version. Sometimes the songs save, but most of the time I cannot move it from one computer to another.

**Comment by mbyrdLCS** [comment]
I know it will not sync media but I set this up yesterday on version 1.9 and it is working great. You do have to manually sync when you are ready to sync by going back inot the cloud settings.

**Comment by EStahr3337** [comment]
> I know it will not sync media but I set this up yesterday on version 1.9 and it is working great. You do have to manually sync when you are ready to sync by going back inot the cloud settings.

Even manually syncing, it isn't saving any of our projects.

**Comment by vassbo** [comment]
There is a change in the next version, so you can choose to download the data from the cloud, when initializing. Maybe it uploaded the projects from the second computer instead of downloading it.

You can try to temporarily enable the option "Disable uploading data" on the second computer, then make sure the main computer has synced, then press the "Sync now" button on the second computer. (If this works you should be able to turn off the toggle again.

**Comment by vassbo** [comment]
Please try it out in the latest prerelease: https://github.com/ChurchApps/FreeShow/releases/tag/v1.2.0
You can try resetting the sync, and adding it again.
