### ISSUE TITLE
Templates Textbox are not static.

### ISSUE THREAD

**Issue by TPaulManohar** [ChurchApps/FreeShow#741]
Hi,

We created templates in freeshow as we need. After created the template, Template are not be static as we created,after clicking template again and again it changing the order. We seen in text items, when we click template, to apply to a show, after again we click the template has changes the order of the text.

Here is the screenshot.
This one, we first time applied the template, here Test line 1 and Test Line 2 are in proper order.
![1](https://github.com/user-attachments/assets/18e6e1c7-f1a2-4ab1-8e71-2d690253500b)

After we clicked again the template Text box order has change to Test Line 2 and Test Line 1
![2](https://github.com/user-attachments/assets/5dbbefcd-64ba-47c2-94e1-3c2af0b1de00)

Why template has changing once we created as we liked it should not change any order. if we need to change we can edit the template in edit tab.

Please change this. If there is any reasons for this please let us know.

Thanks,
Paul.

**Comment by TPaulManohar** [comment]
https://github.com/user-attachments/assets/7c8d5c63-b4f7-4240-b056-716cca9a2836

**Comment by vassbo** [comment]
The reason it toggles between is that FreeShow does not know which textbox in the new template you want the text on, (as you saw in the video when you clicked on the Songs template, the text was initially wrong, because it went from 3 to 2 textboxes), so with this feature you can actually click more to easily get it the way you want!

Also if you leave the same template on a show, and change the styling there is no need to click the template, becuase the change will automatically be applied to the show (with the same order on the textboxes)!

**Comment by TPaulManohar** [comment]
@vassbo ,
Thanks for the answer, right now we got to know why it changing.

**Comment by vassbo** [comment]
Update: From version 1.2.9 the behaviour is changed to only shift the items around if the SHIFT key is held down!

**Comment by TPaulManohar** [comment]
@vassbo This Feature I'm wait for so many days. Thanks for fixed this. 

I updated to v1.2.9, Sometimes mouse clicks also shifting & changing items, even we didn't hold the "SHIFT" Key.

**Comment by vassbo** [comment]
Nice! You will still be able to switch the items right after applying the template, but not anytime else. Not sure if it should stay like that or not.. 🤔
