### ISSUE TITLE
adding a notification overlay for nursery or alerts

### ISSUE THREAD

**Issue by kinghamr** [ChurchApps/FreeShow#749]
Is there a way to add an alert notification box for nursery or a crawl or still overlay?

**Comment by vassbo** [comment]
Yes, create an overlay you want to use, add a textbox with any message, if you select the textbox you can click "Special" to add scrolling effects. I recommend using the "Variable" item, because with that it's simple to create preset alerts in the "Variables" drawer section that can be toggled on/off or easily edited!
