### ISSUE TITLE
[Feature Request] Skip SECTIONS if nothing is typed in them

### ISSUE THREAD

**Issue by Bagel94** [ChurchApps/FreeShow#767]
**Describe the feature**
In regard to the "SECTIONS" feature when building a project. It would be nice if when using the arrow keys to change slides that it ignores the sections, or at least an option to check to make this happen.

As of right now, if a show is followed by a "section" it goes to the section thus making you have to hit the arrow key an extra time to get off of the "SECTION" to move to the first item under that section.

 I imagine that it's this way, due to being able to add notes to the sections, so having it show the notes is great, but only makes sense if you actually add notes to it. Otherwise, it's just another step to get through to keep the flow of the service going.

**Comment by frederickjh** [comment]
@vassbo I am wondering if this was closed because it was fixed or because it would not be fixed. Also wondering if we had a regression on this.

I remember a while ago using next to navigate a project would jump past my sections which have no notes, but now it stops all the time on empty sections even if a trigger action is set for the section of "Next slide" or "Next project item".

**Comment by vassbo** [comment]
@frederickjh I would not have closed as completed without any comments if it was not fixed.
It's a regression due to the new output system, so I can get this fixed again. :)
