### ISSUE TITLE
PDF's act as background only?

### ISSUE THREAD

**Issue by joelgraff** [ChurchApps/FreeShow#796]
I'm sure it's not a bug, but I can't find documentation describing this behavior or how to manage it.  That is, PDFs (as images) act as backgrounds only.  I can't get them to act as legitimate slides.  The issue, of course, is that displaying lyrics will simply overlay the slide, instead of clearing it.  Not a big deal - just remember to turn off the background, but switching to the slides does turn off the lyrics as it takes over both foreground and background.

Current version: 1.2.6
OS: Windows

**Comment by vassbo** [comment]
PDFs are supposed to show in the foreground and clear any background. Converting them to images should make them behave just as backgrounds on normal slides. Not sure I get you exactly, but I'll improve some issues with the way it works at the moment.

**Comment by vassbo** [comment]
I changed it so if a PDF is active and you start a background, or a slide with a background, the PDF will be removed.

**Comment by vassbo** [comment]
All right.

Just to clarify, when clicking a slide only the slide layer will get affected, unless a (background/overlay/audio) layer is present on the slide, (or a background on a previous slide), so backgrounds can be changed independent of a show, but if the show has a background that will be played.

In the case of PDFs they should remove any background and play as the slide layer, and then if playing a slide/background when a PDF is active should clear the PDF, but this was not the case at the moment, so that might have been confusing. Also I guess it makes sense to move it to the "Background" layer, so it will not show up when that layer is turned off.

**Comment by vassbo** [comment]
Let me know how it is in this version: https://github.com/ChurchApps/FreeShow/releases/tag/v1.2.7-beta.1
