### ISSUE TITLE
RELEVANT POINTS FOR IMPROVEMENT

### ISSUE THREAD

**Issue by wagnersong** [ChurchApps/FreeShow#842]
add “macros” feature to help with repetitive functions for volunteers;

project image and video, without having to go to settings and "force exit". Be automatic

insert the timer play within the "Stage" function

**Comment by mwb9aa** [comment]
> add “macros” feature to help with repetitive functions for volunteers;

My understanding is the functions in the drawer work when clicked, not just when attached to the slide.


> project image and video, without having to go to settings and "force exit". Be automatic

I am not clear what you mean.

> insert the timer play within the "Stage" function

My install did not have any predefined functions. It did however have a stage layout I could use. I did need to configure the stage layout to include the time, a countdown to time timer, the current slide text, and the next slide text. Since I used a countdown to time timer, set to my service start time, I did not have to start the timer.

if your needs require a timer to countdown to 0, then you probably should use an action to trigger the timer.

**Comment by vassbo** [comment]
As @mwb9aa mentioned. These functions are already here.

1. Functions>Actions behave like macros and can be triggered directly or from any slide.
2. Not sure what you mean, but you should be able to project image/video easily.
3. You can add timers to your stage layout!
