### ISSUE TITLE
Streamlining Output Switching for Stage Monitors

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/FreeShow#882]
From user Talon:
A way to switch my output on a specific monitor easily. I currently have a stage monitor, we use one output for Lyircs and another once the presenter comes up. it is kinda clunky to have to go to settings and click the always on top tab for one of the outputs. A quicker easier switch would be great. Especially as I have young inexperienced volunteers.

**Additional context**

**Comment by vassbo** [comment]
To Talon: One quick and easy way to change stage layout (instead of "Always on top" with multiple outputs) is to use just one stage output & change this value:
![bilde](https://github.com/user-attachments/assets/b979adb8-1ee4-44ec-9835-ad9a512f5a95)

But I can probably add an action to change the stage output layout as well.

**Comment by vassbo** [comment]
I have actually already added that:
![bilde](https://github.com/user-attachments/assets/ba3f2b4d-1bd3-48b9-b16b-66f6ede307d1)
