### ISSUE TITLE
[Feature Request] Ability to customize shortcuts

### ISSUE THREAD

**Issue by yurividal** [ChurchApps/FreeShow#900]
It would be nice if we could customize the keyboard shortcuts, in order to make it easier for unexpirienced AV operators to transition to freeshow.

Specifically, in my case, i would like to be able to use:

ESC to stop presenting - similar to most other presentation apps, and powerpoint
UP/Down to go to next/previous slide - again, similar to other presentation apps, and powerpoint
PgUp/PgDown to Change Project Item

Maybe these can be active only when a presentation is active, i dont mind.

**Comment by vassbo** [comment]
Escape will clear the output (in a way stop presenting) so that should stay.

I see what you mean with the arrow keys, but I don't think that would be a good idea!

First of all arrow right/left works fine for PowerPoint & most presentation softwares, also in this case.
Arrow up/down is a quick & easy way to navigate the project while presenting with the left/right keys.

The problem is if I were to add a setting to change this like you mentioned it would be bad if someone changed the shortcuts, because if an experienced user used the program and pressed arrow down to change project item & the slide changed instead, this would not be what he expected.

I hope you get what I mean, the shortcuts should be the same to reduce confusion (especially if there are multiple users)!

**Comment by thebiblelover7** [comment]
I believe that the shortcuts *should be* customizable. Allowing them to be customizable would lower the barrier of entry for the new people we would train in our team as the shortcuts would be as they are used to or would make more sense. For some use cases some shortcuts make more sense than others. I think it's easier to add an option to modify keyboard shortcuts than to try and make shortcuts work like everyone wants them to.

I would appreciate it if this would be reconsidered.

**Comment by vassbo** [comment]
@thebiblelover7 What shortcuts would you like to modify?

**Comment by thebiblelover7** [comment]
Practically anything... For example, the shortcut to clear the screen is currently "Esc", to make it easier for my team, it would be better to have "F1" to clear it... not everyone would want this shortcut changed, so I think it's easier to make it customizable...

**Comment by vassbo** [comment]
Okay, but what if two in the team want different shortcuts?

I know for myself I would not like the thought in the middle of service; "Wait.. what if someone has changed this shortcut, and it does not work as I expect?!" - maybe alert the user on startup if custom presentation shortcuts are set.

I see the appeal though (especially for one person users), so if someone codes a working solution I'll probably include it.
(If there is time I might do it myself in the future)

**Comment by Lpwmack17** [comment]
@vassbo Is there any way to implement profiles for hotkeys? It would be like having different layouts that each person using Freeshow can choose from. When opening Freeshow, you could select which profile you want to use, and in that profile, you would have different settings or hotkeys.

This could also be an idea where you have different presentations depending on which profile you are using. It would be helpful for churches that share a congregation with another church, so that everyone has their own settings or preferences for how they want their profile on Freeshow to be.

**Comment by vassbo** [comment]
@Lpwmack17 That is an option. But I won't prioritize it.

In a way you can switch "profiles" in settings>Other by switching data file locations, but I see that can be unintuitive.
