### ISSUE TITLE
[Bug Report] Importing more than 99 songs at once, breaks the songs.

### ISSUE THREAD

**Issue by yurividal** [ChurchApps/FreeShow#907]
I can import 99 songs from OpenSong database, with no problem.

If i try to import 100 or more at a single time, it breaks Freeshow. 
The songs aparently import fine, and all show in the list. But, when you attempt to click any song, you just get a red bar, and it says "Could not find show"

![image](https://github.com/user-attachments/assets/46d53414-3ab1-4d83-9e51-849c38e08915)

I see this in the logs:
````
			"time": "2024-10-15T19:55:35.195Z",
			"os": "win32",
			"version": "1.2.9",
			"active": {
				"window": "main",
				"page": "show",
				"show": {
					"id": "dbc8cb30319",
					"type": "show"
				},
				"edit": {
					"items": []
				}
			},
			"drawer": {
				"active": "shows"
			},
			"type": "unhandledrejection",
			"source": "See stack",
			"message": "Cannot read properties of undefined (reading 'offsetHeight')",
			"stack": "TypeError: Cannot read properties of undefined (reading 'offsetHeight')\n    at file:///C:/Users/yuri/AppData/Local/Programs/freeshow/resources/app.asar/public/build/bundle.js:19:243351"
		},
		{
			"time": "2024-10-15T19:58:57.815Z",
			"os": "win32",
			"version": "1.2.9",
			"active": {
				"window": "main",
				"page": "show",
				"show": {
					"id": "b28599501f9",
					"type": "show"
				},
				"edit": {
					"items": []
				}
			},
			"drawer": {
				"active": "shows"
			},
			"type": "unhandledrejection",
			"source": "See stack",
			"message": "Cannot read properties of undefined (reading 'offsetHeight')",
			"stack": "TypeError: Cannot read properties of undefined (reading 'offsetHeight')\n    at file:///C:/Users/yuri/AppData/Local/Programs/freeshow/resources/app.asar/public/build/bundle.js:19:243351"
		}
	]
}
````

**Comment by vassbo** [comment]
I think the issue does not have something to do with the count (100 or more removes the stored cache to reduce lag, but that just revealed the actual issue).

I think the problem was that you first imported some shows, then deleted them (they are scheduled to be deleted), then imported the same songs again (above 100 will automatically save!), that will create the new shows, then delete them again right away.

I think I managed to fix this by just removing the delete schedule if creating/renaming a show to the same name!
