### ISSUE TITLE
[Feature Request] add option to use libreoffice or WPS besides powerpoint

### ISSUE THREAD

**Issue by gkiibzmultimedia** [ChurchApps/FreeShow#925]
can you add the option to use libreoffice or WPS instead of powerpoint please?

**Comment by vassbo** [comment]
Not until it gets support from the package used: https://github.com/rse/slideshow?tab=readme-ov-file#presentation-application-support-status

But if you do not stream it's just as easy to just present directly with LibreOffice.
It's also free to present with PowerPoint without an account, just not editing, so that can also work.

**Comment by gkiibzmultimedia** [comment]
"It's also free to present with PowerPoint without an account"
where can I get this?

**Comment by vassbo** [comment]
Should come with Windows: https://www.youtube.com/watch?v=XyKhMocUmoo
