### ISSUE TITLE
[Bug Report] Clicking anything in Settings->Other freezes the app

### ISSUE THREAD

**Issue by yurividal** [ChurchApps/FreeShow#935]
When i go to settings -> other, if i try to clik anything, the app freezes and goes to "not responding". If i leave it alone and wait, it comes back after about 1 minute.

![image](https://github.com/user-attachments/assets/ac6e9e55-3853-4c45-ab4d-cf9960d0339f)

Windows 11, 12th Gen Core i7, 16GB RAM, SSD

**Comment by yurividal** [comment]
Could this be related to the fact that i have 3100 songs in the library? maybe its calculating something that is not otomized to handle such volume?

**Comment by mwb9aa** [comment]
@yurividal 

I noticed your Data and Show location are on an I drive and have a long directory structure with lots of spaces. Is the I drive a network or USB drive? If it is, perhaps FreeShow is reconnecting each time. Or, in the event of a large disk, maybe it is reading/loading the entire disk. What happens if the Data and Show location are on a local drive?

**Comment by yurividal** [comment]
@mwb9aa it's a google drive shared drive. But it's synced locally, so all the files are actually on the hard drive, and not elsewhere.

**Comment by yurividal** [comment]
@mwb9aa i have just changed the data and show directory back to the Documents folder, and still the same thing. Between 1-2 seconds to change to a new bible verse slide.

**Comment by mwb9aa** [comment]
@yurividal 

I had an issue with version 1.2.8, I think. I tried to uninstall, then reinstall, and that did not work. I then went poking around  looking for app specific settings in the programs folder, etc. I found them in the user hidden folder. I deleted the files (not folders or files in the folders) and the problem was gone.

C:\\Users\UserName\App Data\Local\FreeShow

If it wasn't the Local folder, it was Roaming and Username is the name of the user logged in to the machine.

**Comment by vassbo** [comment]
It does calculate your shows..
But not sure why it hangs, I have 4000+ songs, and "Other" loads instantly.

**Comment by yurividal** [comment]
@vassbo is there a way to collect debug logs to understand what its doing?

**Comment by vassbo** [comment]
Not as I'm aware of.

**Comment by vassbo** [comment]
Maybe if you could send me a full backup of your files @yurividal, so I can at least see if some of your files are causing it.
You can send to dev@freeshow.app

**Comment by yurividal** [comment]
@vassbo  ok, just sent it

**Comment by vassbo** [comment]
I also got the freeze here you got @yurividal when I imported your files, not sure why I did not get it before.

But I'm pretty sure I got this fixed!
It was reading all shows to check if any were empty, I made it async instead of sync to stop it from freezing, also I added a cap of 1000 shows max to check for that.

**Comment by yurividal** [comment]
you are a rock-star 👏
Quick question: what is the purpose of checking for empty shows?

**Comment by vassbo** [comment]
It is just a utility feature to help users clean unused shows after years of use with many different users.
