### ISSUE TITLE
[Feature Request] {Activate the stage screen}

### ISSUE THREAD

**Issue by Rares006** [ChurchApps/FreeShow#946]
**Describe the feature**
I would like to show the verse only on stage screen
**Additional context**

<img width="162" alt="Screenshot 2024-10-28 at 22 43 10" src="https://github.com/user-attachments/assets/0bcf9248-0930-4df5-98bd-de1cd015f8cd">
Every time during the prayer we show the lyrics only on the stage screen so that those who sing can see what song is coming next, but I don't want it to be seen in the hall and on the live stream until the song starts and I would really like to have a button that when it is enabled to display all the screens that are for the public and one to display only the stage screen. Like the pro presenter

**Comment by mwb9aa** [comment]
I think you can already do this by clicking on the outputs you want to disable in the upper right corner of FreeShow. If you get a message about needing at least one active output, duplicate your audience output, and the manually assign the screen to be outside the range of your current setup. For example, if you have 3 HD (1920x1080) monitor sizes in a row, the primary monitor’s upper left corner is at 0,0 where the first digit is the X coordinate, and the second digit is the Y coordinate. Since the monitors are all in a line, just set the Y value for your duplicate output to be -1080 for above the row or 1081 to be below the row.

To enable the output, click it again.

**Comment by vassbo** [comment]
You should be able to do this with "Actions", create a second stage layout however you would like.
Choose "Change stage layout by ID" to change web stage layouts, or choose "Change stage output layout" for HDMI stage outputs.

**Comment by Rares006** [comment]
![IMG_0958](https://github.com/user-attachments/assets/6f942c43-41bb-4d28-9985-6577a45fb21c)
If it’s possible I like if will be a button like that from the image to activate and deactivate stage screen and this tu remain for the audience outputs.
