### ISSUE TITLE
[Bug Report] {Import powerpoint}

### ISSUE THREAD

**Issue by Rares006** [ChurchApps/FreeShow#956]
**Describe the bug**
I can not import PowerPoint file

**Screenshots (Optional)**
[https://we.tl/t-jjHKHjC0Ni](https://we.tl/t-jjHKHjC0Ni)

**Comment by mwb9aa** [comment]
Your link didn’t work. Would you please expand on can’t import? Do you get a black screen, nothing happens, or garbled text? Did you try to drag and drop or did you do File->Import

**Comment by Rares006** [comment]
I tried it. Can you copy and paste the link?

**Comment by mwb9aa** [comment]
@Rares006 

The video of the pptx importing and showing text all over the place is working as intended (I think), because that method gets only the text and attempts to convert the text to a format that matches your template.

The video of the pptx not working and giving the error that the application isn't started yet refers to the MS PowerPoint application not being available when you clicked Start. After MS PowerPoint opens, I noticed it is in Protected Mode and that product activation failed. I think FreeShow essentially ingests a virtual output for the MS PowerPoint application, the MS PowerPoint application needs to functional first. The file needs to open in MS PowerPoint first.

1. Change the filename to eliminate characters that are letters without accents to avoid any filename issues.
2. Right-click on the file, choose Properties, and choose Unblock OR open the file in MS PowerPoint and click the enable editing message banner near the ribbon.
3. Save the file. Steps 2 and 3 eliminate file access problems.
4. Try to import again. This step verifies a FreeShow problem

Thank for trying those steps.
