### ISSUE TITLE
[Bug Report] {Stage screen issue}

### ISSUE THREAD

**Issue by Rares006** [ChurchApps/FreeShow#957]
[**Describe] the bug**
The stage screen does not display lyrics if one of the other screens is disabled

**Reproducing**
[https://we.tl/t-DW2mDtnI6p](https://we.tl/t-DW2mDtnI6p)

**Comment by mwb9aa** [comment]
Your link does not seem to work.

**Comment by Rares006** [comment]
Now it works

**Comment by mwb9aa** [comment]
I can confirm this behavior.

Steps to reproduce:
1. Create 3 outputs (I did not try more than 3 or NDI), 2 normal and 1 stage.
2. Display a Show from the Drawer or from the project that has more than one slide.
3. Disable either of the normal inputs. (You can do this as step 2 and step 2 as step 3 with the same result).*
4. Click on a slide that is not currently active. For example, slide 3.
5. The stage display does not update (unexpected), neither does the disabled output (expected).
6. The main layout area now has 2 borders around slides indicating they are "active" 1 border is around the slide from step 2 (the first slide), the other border is on slide 3 (from step 4).

Enabling the disabled output from step 3, and then clicking on any slide "restores" the typical behavior.

*The same behavior happens if I disable by clicking the output name or go through settings.

**Comment by vassbo** [comment]
I don't see the issue here..

The stage display will default to the first enabled output (regardless of it's active or not, if no specific stage source output is set).
![bilde](https://github.com/user-attachments/assets/81c5e1f7-2e2a-46d7-9bef-975db2badb57)

If I click the first output so just the second one is active, the stage should not update as the first output has not updated.
If I set the first output active so the second is inactive, the second output won't update (as expected) and the first output & stage ouptut will update.
